### PR TITLE
Added romanian translation

### PR DESCRIPTION
**Pull request by mih44**
Hi, I've added the romanian translation and also changed the code in `i18n.ts` to enable it. The language switcher doesn't seem to work correctly but I have not touched that.

### CODE REVIEW

**Comment by NyaomiDEV** [comment]
There are missing strings, as you've probably translated up to some point in time.

I'll be happy to merge this PR once this translation matches 1:1 with the current English translation.

**Comment by NyaomiDEV** [comment]
> Done, I think that's all, if I missed a file please tell me.

there have been some changes inside options.json for sure; then again, please review each file as I've been really rushing development and I forgot what's changed (also I don't know at which point in time you forked)

**Comment by NyaomiDEV** [comment]
> as mentioned in the commit message - regarding `tagManagement.edit.actions`, if the key is named `desc_other` it doesn't get picked up by the web interface, but if it's called just `desc` it does get picked up.

Please revert `desc` to `desc_other`. If it won't pick that up, we have to fix the actual cause.

**Comment by Ittihadyya** [comment]
> > as mentioned in the commit message - regarding `tagManagement.edit.actions`, if the key is named `desc_other` it doesn't get picked up by the web interface, but if it's called just `desc` it does get picked up.
> 
> Please revert `desc` to `desc_other`. If it won't pick that up, we have to fix the actual cause.

Done.

**Comment by NyaomiDEV** [comment]
... i fucked up

**Comment by Ittihadyya** [comment]
> ... i fucked up

I noticed haha

**Comment by NyaomiDEV** [comment]
whatever, it's in main now

look for it at github pages! and thanks!

**Comment by Ittihadyya** [comment]
> whatever, it's in main now
> 
> look for it at github pages! and thanks!

It works! No problem, glad to be of help!

**Pull request closed without merging**
